services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
        #      args:
        #http_proxy: http://proxy.com
        #https_proxy: https://proxy.com
    restart: unless-stopped
    command: gunicorn intranet.wsgi:application -b :8000 --workers 2 --threads 2 --log-level debug
    depends_on:
      - redis
    volumes:
      - staticfiles:/django/staticfiles
      - mediafiles:/django/media

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - staticfiles:/django/staticfiles:ro
      - mediafiles:/django/media:ro
      - ./config/nginx:/etc/nginx/conf.d

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
  staticfiles:
  mediafiles:
